[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = [
   "build", 
   "-Z", 
   "unstable-options", 
   "--verbose"
]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run]
command = "cargo"
args = [
  "run",
  "-Z",
  "unstable-options",
  "--manifest-path",
  "cmd/monitor/Cargo.toml",
]

[tasks.flow]
dependencies = [
   "format",
   "build",
   "test",
]
