id = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

[discord]
token = 'Bot <TOKEN>'
large_threshold = 20
message_cache_size = 2000
id = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

[giphy]
token = '<TOKEN>'

[matrix]
server = 'https://example.com/'
token = '<TOKEN_HERE>'
id = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
